// import cake from '../../assets/categoryImage/cake.png';
// import cholebhature from '../../assets/categoryImage/cholebhature.png';
// import dosa from '../../assets/categoryImage/dosa.png';
// import icecream from '../../assets/categoryImage/ice-cream.png';
// import idli from '../../assets/categoryImage/idli.png';
// import momos from '../../assets/categoryImage/momos.png';
// import pavbhaji from '../../assets/categoryImage/pavbhaji.png';
// import pizza from '../../assets/categoryImage/pizza.png';
// import plainburger from '../../assets/categoryImage/plainburger.png';
// import samosa from '../../assets/categoryImage/samosa.png';
// import sandwich from '../../assets/categoryImage/sandwich.png';
// import saoji from '../../assets/categoryImage/saoji.png';
// import thali from '../../assets/categoryImage/thali.png';

const RestaurantData = [
  {
    id: 1,
    name: "Pintu Saoji Restaurant",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqSwpR145E7c1qQCeNCIDf1PX9pGJM6IvUlw&s",
    rating: "3.8",
    tags: "Biryani, North Indian",
    distance: "3.9 km",
    priceForTwo: "₹250",
    deliveryTime: "25-30 MINS",
    freeDelivery: true,
    location: "Pratap Nagar",
    dishName: "Saoji",
  },
  {
    id: 2,
    name: "Chinese Hut",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyhrelgj2VUN-uTrk46aiy9wX3QDjLi-bDBA&s",
    rating: "4.3",
    tags: "Chinese, Fast Food",
    distance: "0.5 km",
    priceForTwo: "₹300",
    deliveryTime: "20-25 MINS",
    freeDelivery: true,
    location: "Bajaj Nagar",
    dishName: "Momos",
  },
  {
    id: 3,
    name: "Pizza Planet",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_b18AhX_x9OGzOALgqMRzkatTATIQB3fIww&s",
    rating: "4.5",
    tags: "Pizza, Italian",
    distance: "2.1 km",
    priceForTwo: "₹400",
    deliveryTime: "30-35 MINS",
    freeDelivery: false,
    location: "Koradi",
    dishName: "Pizza",
  },
  {
    id: 4,
    name: "Chole Bhature King",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnv8nOd0cc9Nemr_y1JLV41wTUUBg3vYAq2w&s",
    rating: "4.2",
    tags: "Punjabi, North Indian",
    distance: "1.2 km",
    priceForTwo: "₹200",
    deliveryTime: "15-20 MINS",
    freeDelivery: true,
    location: "Mahal",
    dishName: "Chole",
  },
  {
    id: 5,
    name: "Dosa Delight",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7P9-ECimzMDQMWGiu2XnSWErvEqRmz5rTaw&s",
    rating: "4.6",
    tags: "South Indian",
    distance: "2.8 km",
    priceForTwo: "₹180",
    deliveryTime: "20-25 MINS",
    freeDelivery: false,
    location: "Laxmi Nagar",
    dishName: "Dosa",
  },
  {
    id: 6,
    name: "Samosa Junction",
    image:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/12/samosa-recipe.jpg",
    rating: "4.0",
    tags: "Snacks, Fast Food",
    distance: "1.5 km",
    priceForTwo: "₹100",
    deliveryTime: "10-15 MINS",
    freeDelivery: true,
    location: "Mankapur",
    dishName: "Samosa",
  },
  {
    id: 7,
    name: "Burger Hub",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuoS6_wIXY5dx2M4H88TE4UhSXA87yaOtz7w&s",
    rating: "4.4",
    tags: "Burgers, Fast Food",
    distance: "3.0 km",
    priceForTwo: "₹350",
    deliveryTime: "25-30 MINS",
    freeDelivery: false,
    location: "Mankapur",
    dishName: "IceCream",
  },
  {
    id: 8,
    name: "Paneer Paradise",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJ35Bs4lyhxKgPTt9qL5z1KZPzeQaSyiUvzw&s",
    rating: "4.1",
    tags: "Paneer Dishes",
    distance: "2.4 km",
    priceForTwo: "₹280",
    deliveryTime: "20-25 MINS",
    freeDelivery: true,
    location: "Ambazari",
    dishName: "Paneer",
  },
  {
    id: 9,
    name: "Ice Cream Factory",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN2bed8h7eVqZcOaNrCCFYEKRSYwsRJQZ9Rg&s",
    rating: "4.7",
    tags: "Desserts, Ice Cream",
    distance: "2.0 km",
    priceForTwo: "₹150",
    deliveryTime: "15-20 MINS",
    freeDelivery: true,
    location: "Mankapur",
    dishName: "Momos",
  },
  {
    id: 10,
    name: "Rolls Corner",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6DslmYNmoKF1TEhbQd2KpMEVTjCM3VUWEXw&s",
    rating: "4.3",
    tags: "Rolls, Wraps",
    distance: "1.8 km",
    priceForTwo: "₹220",
    deliveryTime: "20-25 MINS",
    freeDelivery: false,
    location: "Pratap Nagar",
    dishName: "Rolls",
  },
  {
    id: 11,
    name: "Thali Junction",
    image:
      "https://content.jdmagicbox.com/v2/comp/mumbai/n4/022pxx22.xx22.190131150924.y2n4/catalogue/thalis-of-india-chembur-mumbai-home-delivery-restaurants-odew9zikwf.jpg",
    rating: "4.5",
    tags: "North Indian, Thali",
    distance: "2.5 km",
    priceForTwo: "₹300",
    deliveryTime: "25-30 MINS",
    freeDelivery: true,
    location: "Sitabuldi",
    dishName: "Thali",
  },
  {
    id: 12,
    name: "Cake Walk",
    image:
      "https://theobroma.in/cdn/shop/files/BlackForestCake_400x400.jpg?v=1750341419",
    rating: "4.8",
    tags: "Bakery, Desserts",
    distance: "1.0 km",
    priceForTwo: "₹500",
    deliveryTime: "30-35 MINS",
    freeDelivery: false,
    location: "Civil Lines",
    dishName: "Cake",
  },
  {
    id: 13,
    name: "Pav Bhaji House",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKhv9wsRRqtdGNvC--uQ3Yctnjh2XRZJ0Mfw&s",
    rating: "4.2",
    tags: "Fast Food, Mumbai Special",
    distance: "3.2 km",
    priceForTwo: "₹240",
    deliveryTime: "25-30 MINS",
    freeDelivery: true,
    location: "Civil Lines",
    dishName: "PavBhaji",
  },
  {
    id: 14,
    name: "Idli World",
    image:
      "https://www.awesomecuisine.com/wp-content/uploads/2007/11/Idli-with-sambar-and-chutney.jpg",
    rating: "4.1",
    tags: "South Indian",
    distance: "2.0 km",
    priceForTwo: "₹160",
    deliveryTime: "20-25 MINS",
    freeDelivery: false,
    location: "Mahal",
    dishName: "Idli",
  },
  {
    id: 15,
    name: "Momos Point",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVPvcZIxeA9bZukK18CymY32OqFUTVbkKXgQ&s",
    rating: "4.4",
    tags: "Chinese, Snacks",
    distance: "1.7 km",
    priceForTwo: "₹200",
    deliveryTime: "15-20 MINS",
    freeDelivery: true,
    location: "Mankapur",
  },
  {
    id: 16,
    name: "Shravan Specials",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQULDPkJ8PfjDLulqB88WVtf4NmF2X_EurAIg&s",
    rating: "4.6",
    tags: "Pure Veg, Fasting",
    distance: "2.5 km",
    priceForTwo: "₹280",
    deliveryTime: "20-25 MINS",
    freeDelivery: false,
    location: "Dharampeth",
    dishName: "Specials",
  },
  {
    id: 17,
    name: "Chaat Bazaar",
    image:
      "https://c.ndtvimg.com/2022-02/o9a9hsuo_papadi-chaat_650x300_26_February_22.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350?im=FaceCrop,algorithm=dnn,width=1200,height=886",
    rating: "4.3",
    tags: "Chaat, Street Food",
    distance: "1.9 km",
    priceForTwo: "₹150",
    deliveryTime: "10-15 MINS",
    freeDelivery: true,
    location: "Laxmi Nagar",
    dishName: "Chaat",
  },
  {
    id: 18,
    name: "Wrap & Roll",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6DslmYNmoKF1TEhbQd2KpMEVTjCM3VUWEXw&s",
    rating: "4.2",
    tags: "Wraps, Fast Food",
    distance: "2.8 km",
    priceForTwo: "₹220",
    deliveryTime: "20-25 MINS",
    freeDelivery: false,
    location: "Trimurti Nagar",
    dishName: "Wrap",
  },
  {
    id: 19,
    name: "Burger Blast",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuoS6_wIXY5dx2M4H88TE4UhSXA87yaOtz7w&s",
    rating: "4.4",
    tags: "Burgers, Snacks",
    distance: "3.0 km",
    priceForTwo: "₹320",
    deliveryTime: "25-30 MINS",
    freeDelivery: true,
    location: "Wardhaman Nagar",
    dishName: "Burger",
  },
  {
    id: 20,
    name: "Paneer Palace",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJ35Bs4lyhxKgPTt9qL5z1KZPzeQaSyiUvzw&s",
    rating: "4.5",
    tags: "Paneer Specials, North Indian",
    distance: "2.3 km",
    priceForTwo: "₹300",
    deliveryTime: "25-30 MINS",
    freeDelivery: false,
    location: "Dharampeth",
    dishName: "Paneer",
  },
];

export default RestaurantData;
